from framework.model.SIG import *


def check_if_uuid_predefined(uuid):
    # Get the first part of the UUID xxxxxxxx and remove any leading zeros
    # and pad it back up to 4 characters most likely unnecessary but better
    # to be safe than sorry :)
    key = "{0:0{1}x}".format(int(uuid.split('-')[0], 16), 4)
    for sig_item in sig_items:
        if key in sig_item:
            return sig_item[key]

    # There are some special item where the two byte part of the UUID might
    # not cut it, so we go with the full UUID
    for custom_item in custom_items:
        if uuid in custom_item:
            return custom_item[uuid]

    return None


characteristics = {
    '2a7e': Characteristic('Aerobic Heart Rate Lower Limit',
                           'org.bluetooth.characteristic.aerobic_heart_rate_lower_limit'),
    '2a84': Characteristic('Aerobic Heart Rate Upper Limit',
                           'org.bluetooth.characteristic.aerobic_heart_rate_upper_limit'),
    '2a7f': Characteristic('Aerobic Threshold',
                           'org.bluetooth.characteristic.aerobic_threshold'),
    '2a80': Characteristic('Age', 'org.bluetooth.characteristic.age'),
    '2a5a': Characteristic('Aggregate',
                           'org.bluetooth.characteristic.aggregate'),
    '2a43': Characteristic('Alert Category ID',
                           'org.bluetooth.characteristic.alert_category_id'),
    '2a42': Characteristic('Alert Category ID Bit Mask',
                           'org.bluetooth.characteristic.alert_category_id_bit_mask'),
    '2a06': Characteristic('Alert Level',
                           'org.bluetooth.characteristic.alert_level'),
    '2a44': Characteristic('Alert Notification Control Point',
                           'org.bluetooth.characteristic.alert_notification_control_point'),
    '2a3f': Characteristic('Alert Status',
                           'org.bluetooth.characteristic.alert_status'),
    '2ab3': Characteristic('Altitude',
                           'org.bluetooth.characteristic.altitude'),
    '2a81': Characteristic('Anaerobic Heart Rate Lower Limit',
                           'org.bluetooth.characteristic.anaerobic_heart_rate_lower_limit'),
    '2a82': Characteristic('Anaerobic Heart Rate Upper Limit',
                           'org.bluetooth.characteristic.anaerobic_heart_rate_upper_limit'),
    '2a83': Characteristic('Anaerobic Threshold',
                           'org.bluetooth.characteristic.anaerobic_threshold'),
    '2a58': Characteristic('Analog', 'org.bluetooth.characteristic.analog'),
    '2a59': Characteristic('Analog Output',
                           'org.bluetooth.characteristic.analog_output'),
    '2a73': Characteristic('Apparent Wind Direction',
                           'org.bluetooth.characteristic.apparent_wind_direction'),
    '2a72': Characteristic('Apparent Wind Speed',
                           'org.bluetooth.characteristic.apparent_wind_speed'),
    '2a01': Characteristic('Appearance',
                           'org.bluetooth.characteristic.gap.appearance'),
    '2aa3': Characteristic('Barometric Pressure Trend',
                           'org.bluetooth.characteristic.barometric_pressure_trend'),
    '2a19': Characteristic('Battery Level',
                           'org.bluetooth.characteristic.battery_level'),
    '2a1b': Characteristic('Battery Level State',
                           'org.bluetooth.characteristic.battery_level_state'),
    '2a1a': Characteristic('Battery Power State',
                           'org.bluetooth.characteristic.battery_power_state'),
    '2a49': Characteristic('Blood Pressure Feature',
                           'org.bluetooth.characteristic.blood_pressure_feature'),
    '2a35': Characteristic('Blood Pressure Measurement',
                           'org.bluetooth.characteristic.blood_pressure_measurement'),
    '2a9b': Characteristic('Body Composition Feature',
                           'org.bluetooth.characteristic.body_composition_feature'),
    '2a9c': Characteristic('Body Composition Measurement',
                           'org.bluetooth.characteristic.body_composition_measurement'),
    '2a38': Characteristic('Body Sensor Location',
                           'org.bluetooth.characteristic.body_sensor_location'),
    '2aa4': Characteristic('Bond Management Control Point',
                           'org.bluetooth.characteristic.bond_management_control_point'),
    '2aa5': Characteristic('Bond Management Features',
                           'org.bluetooth.characteristic.bond_management_feature'),
    '2a22': Characteristic('Boot Keyboard Input Report',
                           'org.bluetooth.characteristic.boot_keyboard_input_report'),
    '2a32': Characteristic('Boot Keyboard Output Report',
                           'org.bluetooth.characteristic.boot_keyboard_output_report'),
    '2a33': Characteristic('Boot Mouse Input Report',
                           'org.bluetooth.characteristic.boot_mouse_input_report'),
    '2aa6': Characteristic('Central Address Resolution',
                           'org.bluetooth.characteristic.gap.central_address_resolution'),
    '2aa8': Characteristic('CGM Feature',
                           'org.bluetooth.characteristic.cgm_feature'),
    '2aa7': Characteristic('CGM Measurement',
                           'org.bluetooth.characteristic.cgm_measurement'),
    '2aab': Characteristic('CGM Session Run Time',
                           'org.bluetooth.characteristic.cgm_session_run_time'),
    '2aaa': Characteristic('CGM Session Start Time',
                           'org.bluetooth.characteristic.cgm_session_start_time'),
    '2aac': Characteristic('CGM Specific Ops Control Point',
                           'org.bluetooth.characteristic.cgm_specific_ops_control_point'),
    '2aa9': Characteristic('CGM Status',
                           'org.bluetooth.characteristic.cgm_status'),
    '2b29': Characteristic('Client Supported Features',
                           'org.bluetooth.characteristic.client_supported_features'),
    '2ace': Characteristic('Cross Trainer Data',
                           'org.bluetooth.characteristic.cross_trainer_data'),
    '2a5c': Characteristic('CSC Feature',
                           'org.bluetooth.characteristic.csc_feature'),
    '2a5b': Characteristic('CSC Measurement',
                           'org.bluetooth.characteristic.csc_measurement'),
    '2a2b': Characteristic('Current Time',
                           'org.bluetooth.characteristic.current_time'),
    '2a66': Characteristic('Cycling Power Control Point',
                           'org.bluetooth.characteristic.cycling_power_control_point'),
    '2a65': Characteristic('Cycling Power Feature',
                           'org.bluetooth.characteristic.cycling_power_feature'),
    '2a63': Characteristic('Cycling Power Measurement',
                           'org.bluetooth.characteristic.cycling_power_measurement'),
    '2a64': Characteristic('Cycling Power Vector',
                           'org.bluetooth.characteristic.cycling_power_vector'),
    '2a99': Characteristic('Database Change Increment',
                           'org.bluetooth.characteristic.database_change_increment'),
    '2b2a': Characteristic('Database Hash',
                           'org.bluetooth.characteristic.database_hash'),
    '2a85': Characteristic('Date of Birth',
                           'org.bluetooth.characteristic.date_of_birth'),
    '2a86': Characteristic('Date of Threshold Assessment',
                           'org.bluetooth.characteristic.date_of_threshold_assessment'),
    '2a08': Characteristic('Date Time',
                           'org.bluetooth.characteristic.date_time'),
    '2aed': Characteristic('Date UTC',
                           'org.bluetooth.characteristic.date_utc'),
    '2a0a': Characteristic('Day Date Time',
                           'org.bluetooth.characteristic.day_date_time'),
    '2a09': Characteristic('Day of Week',
                           'org.bluetooth.characteristic.day_of_week'),
    '2a7d': Characteristic('Descriptor Value Changed',
                           'org.bluetooth.characteristic.descriptor_value_changed'),
    '2a00': Characteristic('Device Name',
                           'org.bluetooth.characteristic.gap.device_name'),
    '2a7b': Characteristic('Dew Point',
                           'org.bluetooth.characteristic.dew_point'),
    '2a56': Characteristic('Digital', 'org.bluetooth.characteristic.digital'),
    '2a57': Characteristic('Digital Output',
                           'org.bluetooth.characteristic.digital_output'),
    '2a0d': Characteristic('DST Offset',
                           'org.bluetooth.characteristic.dst_offset'),
    '2a6c': Characteristic('Elevation',
                           'org.bluetooth.characteristic.elevation'),
    '2a87': Characteristic('Email Address',
                           'org.bluetooth.characteristic.email_address'),
    '2a0b': Characteristic('Exact Time 100',
                           'org.bluetooth.characteristic.exact_time_100'),
    '2a0c': Characteristic('Exact Time 256',
                           'org.bluetooth.characteristic.exact_time_256'),
    '2a88': Characteristic('Fat Burn Heart Rate Lower Limit',
                           'org.bluetooth.characteristic.fat_burn_heart_rate_lower_limit'),
    '2a89': Characteristic('Fat Burn Heart Rate Upper Limit',
                           'org.bluetooth.characteristic.fat_burn_heart_rate_upper_limit'),
    '2a26': Characteristic('Firmware Revision String',
                           'org.bluetooth.characteristic.firmware_revision_string'),
    '2a8a': Characteristic('First Name',
                           'org.bluetooth.characteristic.first_name'),
    '2ad9': Characteristic('Fitness Machine Control Point',
                           'org.bluetooth.characteristic.fitness_machine_control_point'),
    '2acc': Characteristic('Fitness Machine Feature',
                           'org.bluetooth.characteristic.fitness_machine_feature'),
    '2ada': Characteristic('Fitness Machine Status',
                           'org.bluetooth.characteristic.fitness_machine_status'),
    '2a8b': Characteristic('Five Zone Heart Rate Limits',
                           'org.bluetooth.characteristic.five_zone_heart_rate_limits'),
    '2ab2': Characteristic('Floor Number',
                           'org.bluetooth.characteristic.floor_number'),
    '2a8c': Characteristic('Gender', 'org.bluetooth.characteristic.gender'),
    '2a51': Characteristic('Glucose Feature',
                           'org.bluetooth.characteristic.glucose_feature'),
    '2a18': Characteristic('Glucose Measurement',
                           'org.bluetooth.characteristic.glucose_measurement'),
    '2a34': Characteristic('Glucose Measurement Context',
                           'org.bluetooth.characteristic.glucose_measurement_context'),
    '2a74': Characteristic('Gust Factor',
                           'org.bluetooth.characteristic.gust_factor'),
    '2a27': Characteristic('Hardware Revision String',
                           'org.bluetooth.characteristic.hardware_revision_string'),
    '2a39': Characteristic('Heart Rate Control Point',
                           'org.bluetooth.characteristic.heart_rate_control_point'),
    '2a8d': Characteristic('Heart Rate Max',
                           'org.bluetooth.characteristic.heart_rate_max'),
    '2a37': Characteristic('Heart Rate Measurement',
                           'org.bluetooth.characteristic.heart_rate_measurement'),
    '2a7a': Characteristic('Heat Index',
                           'org.bluetooth.characteristic.heat_index'),
    '2a8e': Characteristic('Height', 'org.bluetooth.characteristic.height'),
    '2a4c': Characteristic('HID Control Point',
                           'org.bluetooth.characteristic.hid_control_point'),
    '2a4a': Characteristic('HID Information',
                           'org.bluetooth.characteristic.hid_information'),
    '2a8f': Characteristic('Hip Circumference',
                           'org.bluetooth.characteristic.hip_circumference'),
    '2aba': Characteristic('HTTP Control Point',
                           'org.bluetooth.characteristic.http_control_point'),
    '2ab9': Characteristic('HTTP Entity Body',
                           'org.bluetooth.characteristic.http_entity_body'),
    '2ab7': Characteristic('HTTP Headers',
                           'org.bluetooth.characteristic.http_headers'),
    '2ab8': Characteristic('HTTP Status Code',
                           'org.bluetooth.characteristic.http_status_code'),
    '2abb': Characteristic('HTTPS Security',
                           'org.bluetooth.characteristic.https_security'),
    '2a6f': Characteristic('Humidity',
                           'org.bluetooth.characteristic.humidity'),
    '2b22': Characteristic('IDD Annunciation Status',
                           'org.bluetooth.characteristic.idd_annunciation_status'),
    '2b25': Characteristic('IDD Command Control Point',
                           'org.bluetooth.characteristic.idd_command_control_point'),
    '2b26': Characteristic('IDD Command Data',
                           'org.bluetooth.characteristic.idd_command_data'),
    '2b23': Characteristic('IDD Features',
                           'org.bluetooth.characteristic.idd_features'),
    '2b28': Characteristic('IDD History Data',
                           'org.bluetooth.characteristic.idd_history_data'),
    '2b27': Characteristic('IDD Record Access Control Point',
                           'org.bluetooth.characteristic.idd_record_access_control_point'),
    '2b21': Characteristic('IDD Status',
                           'org.bluetooth.characteristic.idd_status'),
    '2b20': Characteristic('IDD Status Changed',
                           'org.bluetooth.characteristic.idd_status_changed'),
    '2b24': Characteristic('IDD Status Reader Control Point',
                           'org.bluetooth.characteristic.idd_status_reader_control_point'),
    '2a2a': Characteristic(
        'IEEE 11073-20601 Regulatory Certification Data List',
        'org.bluetooth.characteristic.ieee_11073-20601_regulatory_certification_data_list'),
    '2ad2': Characteristic('Indoor Bike Data',
                           'org.bluetooth.characteristic.indoor_bike_data'),
    '2aad': Characteristic('Indoor Positioning Configuration',
                           'org.bluetooth.characteristic.indoor_positioning_configuration'),
    '2a36': Characteristic('Intermediate Cuff Pressure',
                           'org.bluetooth.characteristic.intermediate_cuff_pressure'),
    '2a1e': Characteristic('Intermediate Temperature',
                           'org.bluetooth.characteristic.intermediate_temperature'),
    '2a77': Characteristic('Irradiance',
                           'org.bluetooth.characteristic.irradiance'),
    '2aa2': Characteristic('Language',
                           'org.bluetooth.characteristic.language'),
    '2a90': Characteristic('Last Name',
                           'org.bluetooth.characteristic.last_name'),
    '2aae': Characteristic('Latitude',
                           'org.bluetooth.characteristic.latitude'),
    '2a6b': Characteristic('LN Control Point',
                           'org.bluetooth.characteristic.ln_control_point'),
    '2a6a': Characteristic('LN Feature',
                           'org.bluetooth.characteristic.ln_feature'),
    '2ab1': Characteristic('Local East Coordinate',
                           'org.bluetooth.characteristic.local_east_coordinate'),
    '2ab0': Characteristic('Local North Coordinate',
                           'org.bluetooth.characteristic.local_north_coordinate'),
    '2a0f': Characteristic('Local Time Information',
                           'org.bluetooth.characteristic.local_time_information'),
    '2a67': Characteristic('Location and Speed Characteristic',
                           'org.bluetooth.characteristic.location_and_speed'),
    '2ab5': Characteristic('Location Name',
                           'org.bluetooth.characteristic.location_name'),
    '2aaf': Characteristic('Longitude',
                           'org.bluetooth.characteristic.Longitude'),
    '2a2c': Characteristic('Magnetic Declination',
                           'org.bluetooth.characteristic.magnetic_declination'),
    '2aa0': Characteristic('Magnetic Flux Density - 2D',
                           'org.bluetooth.characteristic.Magnetic_flux_density_2D'),
    '2aa1': Characteristic('Magnetic Flux Density - 3D',
                           'org.bluetooth.characteristic.Magnetic_flux_density_3D'),
    '2a29': Characteristic('Manufacturer Name String',
                           'org.bluetooth.characteristic.manufacturer_name_string'),
    '2a91': Characteristic('Maximum Recommended Heart Rate',
                           'org.bluetooth.characteristic.maximum_recommended_heart_rate'),
    '2a21': Characteristic('Measurement Interval',
                           'org.bluetooth.characteristic.measurement_interval'),
    '2a24': Characteristic('Model Number String',
                           'org.bluetooth.characteristic.model_number_string'),
    '2a68': Characteristic('Navigation',
                           'org.bluetooth.characteristic.navigation'),
    '2a3e': Characteristic('Network Availability',
                           'org.bluetooth.characteristic.network_availability'),
    '2a46': Characteristic('New Alert',
                           'org.bluetooth.characteristic.new_alert'),
    '2ac5': Characteristic('Object Action Control Point',
                           'org.bluetooth.characteristic.object_action_control_point'),
    '2ac8': Characteristic('Object Changed',
                           'org.bluetooth.characteristic.object_changed'),
    '2ac1': Characteristic('Object First-Created',
                           'org.bluetooth.characteristic.object_first_created'),
    '2ac3': Characteristic('Object ID',
                           'org.bluetooth.characteristic.object_id'),
    '2ac2': Characteristic('Object Last-Modified',
                           'org.bluetooth.characteristic.object_last_modified'),
    '2ac6': Characteristic('Object List Control Point',
                           'org.bluetooth.characteristic.object_list_control_point'),
    '2ac7': Characteristic('Object List Filter',
                           'org.bluetooth.characteristic.object_list_filter'),
    '2abe': Characteristic('Object Name',
                           'org.bluetooth.characteristic.object_name'),
    '2ac4': Characteristic('Object Properties',
                           'org.bluetooth.characteristic.object_properties'),
    '2ac0': Characteristic('Object Size',
                           'org.bluetooth.characteristic.object_size'),
    '2abf': Characteristic('Object Type',
                           'org.bluetooth.characteristic.object_type'),
    '2abd': Characteristic('OTS Feature',
                           'org.bluetooth.characteristic.ots_feature'),
    '2a04': Characteristic('Peripheral Preferred Connection Parameters',
                           'org.bluetooth.characteristic.gap.peripheral_preferred_connection_parameters'),
    '2a02': Characteristic('Peripheral Privacy Flag',
                           'org.bluetooth.characteristic.gap.peripheral_privacy_flag'),
    '2a5f': Characteristic('PLX Continuous Measurement Characteristic',
                           'org.bluetooth.characteristic.plx_continuous_measurement'),
    '2a60': Characteristic('PLX Features',
                           'org.bluetooth.characteristic.plx_features'),
    '2a5e': Characteristic('PLX Spot-Check Measurement',
                           'org.bluetooth.characteristic.plx_spot_check_measurement'),
    '2a50': Characteristic('PnP ID', 'org.bluetooth.characteristic.pnp_id'),
    '2a75': Characteristic('Pollen Concentration',
                           'org.bluetooth.characteristic.pollen_concentration'),
    '2a2f': Characteristic('Position 2D',
                           'org.bluetooth.characteristic.position_2d'),
    '2a30': Characteristic('Position 3D',
                           'org.bluetooth.characteristic.position_3d'),
    '2a69': Characteristic('Position Quality',
                           'org.bluetooth.characteristic.position_quality'),
    '2a6d': Characteristic('Pressure',
                           'org.bluetooth.characteristic.pressure'),
    '2a4e': Characteristic('Protocol Mode',
                           'org.bluetooth.characteristic.protocol_mode'),
    '2a62': Characteristic('Pulse Oximetry Control Point',
                           'org.bluetooth.characteristic.pulse_oximetry_control_point'),
    '2a78': Characteristic('Rainfall',
                           'org.bluetooth.characteristic.rainfall'),
    '2b1d': Characteristic('RC Feature',
                           'org.bluetooth.characteristic.rc_feature'),
    '2b1e': Characteristic('RC Settings',
                           'org.bluetooth.characteristic.rc_settings'),
    '2a03': Characteristic('Reconnection Address',
                           'org.bluetooth.characteristic.gap.reconnection_address'),
    '2b1f': Characteristic('Reconnection Configuration Control Point',
                           'org.bluetooth.characteristic.reconnection_configuration_control_point'),
    '2a52': Characteristic('Record Access Control Point',
                           'org.bluetooth.characteristic.record_access_control_point'),
    '2a14': Characteristic('Reference Time Information',
                           'org.bluetooth.characteristic.reference_time_information'),
    '2a3a': Characteristic('Removable',
                           'org.bluetooth.characteristic.removable'),
    '2a4d': Characteristic('Report', 'org.bluetooth.characteristic.report'),
    '2a4b': Characteristic('Report Map',
                           'org.bluetooth.characteristic.report_map'),
    '2ac9': Characteristic('Resolvable Private Address Only',
                           'org.bluetooth.characteristic.resolvable_private_address_only'),
    '2a92': Characteristic('Resting Heart Rate',
                           'org.bluetooth.characteristic.resting_heart_rate'),
    '2a40': Characteristic('Ringer Control point',
                           'org.bluetooth.characteristic.ringer_control_point'),
    '2a41': Characteristic('Ringer Setting',
                           'org.bluetooth.characteristic.ringer_setting'),
    '2ad1': Characteristic('Rower Data',
                           'org.bluetooth.characteristic.rower_data'),
    '2a54': Characteristic('RSC Feature',
                           'org.bluetooth.characteristic.rsc_feature'),
    '2a53': Characteristic('RSC Measurement',
                           'org.bluetooth.characteristic.rsc_measurement'),
    '2a55': Characteristic('SC Control Point',
                           'org.bluetooth.characteristic.sc_control_point'),
    '2a4f': Characteristic('Scan Interval Window',
                           'org.bluetooth.characteristic.scan_interval_window'),
    '2a31': Characteristic('Scan Refresh',
                           'org.bluetooth.characteristic.scan_refresh'),
    '2a3c': Characteristic('Scientific Temperature Celsius',
                           'org.bluetooth.characteristic.scientific_temperature_celsius'),
    '2a10': Characteristic('Secondary Time Zone',
                           'org.bluetooth.characteristic.secondary_time_zone'),
    '2a5d': Characteristic('Sensor Location',
                           'org.bluetooth.characteristic.sensor_location'),
    '2a25': Characteristic('Serial Number String',
                           'org.bluetooth.characteristic.serial_number_string'),
    '2a05': Characteristic('Service Changed',
                           'org.bluetooth.characteristic.gatt.service_changed'),
    '2a3b': Characteristic('Service Required',
                           'org.bluetooth.characteristic.service_required'),
    '2a28': Characteristic('Software Revision String',
                           'org.bluetooth.characteristic.software_revision_string'),
    '2a93': Characteristic('Sport Type for Aerobic and Anaerobic Thresholds',
                           'org.bluetooth.characteristic.sport_type_for_aerobic_and_anaerobic_thresholds'),
    '2ad0': Characteristic('Stair Climber Data',
                           'org.bluetooth.characteristic.stair_climber_data'),
    '2acf': Characteristic('Step Climber Data',
                           'org.bluetooth.characteristic.step_climber_data'),
    '2a3d': Characteristic('String', 'org.bluetooth.characteristic.string'),
    '2ad7': Characteristic('Supported Heart Rate Range',
                           'org.bluetooth.characteristic.supported_heart_rate_range'),
    '2ad5': Characteristic('Supported Inclination Range',
                           'org.bluetooth.characteristic.supported_inclination_range'),
    '2a47': Characteristic('Supported New Alert Category',
                           'org.bluetooth.characteristic.supported_new_alert_category'),
    '2ad8': Characteristic('Supported Power Range',
                           'org.bluetooth.characteristic.supported_power_range'),
    '2ad6': Characteristic('Supported Resistance Level Range',
                           'org.bluetooth.characteristic.supported_resistance_level_range'),
    '2ad4': Characteristic('Supported Speed Range',
                           'org.bluetooth.characteristic.supported_speed_range'),
    '2a48': Characteristic('Supported Unread Alert Category',
                           'org.bluetooth.characteristic.supported_unread_alert_category'),
    '2a23': Characteristic('System ID',
                           'org.bluetooth.characteristic.system_id'),
    '2abc': Characteristic('TDS Control Point',
                           'org.bluetooth.characteristic.tds_control_point'),
    '2a6e': Characteristic('Temperature',
                           'org.bluetooth.characteristic.temperature'),
    '2a1f': Characteristic('Temperature Celsius',
                           'org.bluetooth.characteristic.temperature_celsius'),
    '2a20': Characteristic('Temperature Fahrenheit',
                           'org.bluetooth.characteristic.temperature_fahrenheit'),
    '2a1c': Characteristic('Temperature Measurement',
                           'org.bluetooth.characteristic.temperature_measurement'),
    '2a1d': Characteristic('Temperature Type',
                           'org.bluetooth.characteristic.temperature_type'),
    '2a94': Characteristic('Three Zone Heart Rate Limits',
                           'org.bluetooth.characteristic.three_zone_heart_rate_limits'),
    '2a12': Characteristic('Time Accuracy',
                           'org.bluetooth.characteristic.time_accuracy'),
    '2a15': Characteristic('Time Broadcast',
                           'org.bluetooth.characteristic.time_broadcast'),
    '2a13': Characteristic('Time Source',
                           'org.bluetooth.characteristic.time_source'),
    '2a16': Characteristic('Time Update Control Point',
                           'org.bluetooth.characteristic.time_update_control_point'),
    '2a17': Characteristic('Time Update State',
                           'org.bluetooth.characteristic.time_update_state'),
    '2a11': Characteristic('Time with DST',
                           'org.bluetooth.characteristic.time_with_dst'),
    '2a0e': Characteristic('Time Zone',
                           'org.bluetooth.characteristic.time_zone'),
    '2ad3': Characteristic('Training Status',
                           'org.bluetooth.characteristic.training_status'),
    '2acd': Characteristic('Treadmill Data',
                           'org.bluetooth.characteristic.treadmill_data'),
    '2a71': Characteristic('True Wind Direction',
                           'org.bluetooth.characteristic.true_wind_direction'),
    '2a70': Characteristic('True Wind Speed',
                           'org.bluetooth.characteristic.true_wind_speed'),
    '2a95': Characteristic('Two Zone Heart Rate Limit',
                           'org.bluetooth.characteristic.two_zone_heart_rate_limit'),
    '2a07': Characteristic('Tx Power Level',
                           'org.bluetooth.characteristic.tx_power_level'),
    '2ab4': Characteristic('Uncertainty',
                           'org.bluetooth.characteristic.uncertainty'),
    '2a45': Characteristic('Unread Alert Status',
                           'org.bluetooth.characteristic.unread_alert_status'),
    '2ab6': Characteristic('URI', 'org.bluetooth.characteristic.uri'),
    '2a9f': Characteristic('User Control Point',
                           'org.bluetooth.characteristic.user_control_point'),
    '2a9a': Characteristic('User Index',
                           'org.bluetooth.characteristic.user_index'),
    '2a76': Characteristic('UV Index',
                           'org.bluetooth.characteristic.uv_index'),
    '2a96': Characteristic('VO2 Max', 'org.bluetooth.characteristic.vo2_max'),
    '2a97': Characteristic('Waist Circumference',
                           'org.bluetooth.characteristic.waist_circumference'),
    '2a98': Characteristic('Weight', 'org.bluetooth.characteristic.weight'),
    '2a9d': Characteristic('Weight Measurement',
                           'org.bluetooth.characteristic.weight_measurement'),
    '2a9e': Characteristic('Weight Scale Feature',
                           'org.bluetooth.characteristic.weight_scale_feature'),
    '2a79': Characteristic('Wind Chill',
                           'org.bluetooth.characteristic.wind_chill')
}

members = {
    'fda3': Member('Inseego Corp.'),
    'fda4': Member('Inseego Corp.'),
    'fda5': Member('Neurostim OAB, Inc.'),
    'fda6': Member('WWZN Information Technology Company Limited'),
    'fda7': Member('WWZN Information Technology Company Limited'),
    'fda8': Member('PSA Peugeot Citron'),
    'fda9': Member('Rhombus Systems, Inc.'),
    'fdaa': Member('Xiaomi Inc.'),
    'fdab': Member('Xiaomi Inc.'),
    'fdac': Member('Tentacle Sync GmbH'),
    'fdad': Member('Houwa System Design, k.k.'),
    'fdae': Member('Houwa System Design, k.k.'),
    'fdaf': Member('Wiliot LTD'),
    'fdb0': Member('Proxy Technologies, Inc.'),
    'fdb1': Member('Proxy Technologies, Inc.'),
    'fdb2': Member('Portable Multimedia Ltd'),
    'fdb3': Member('Audiodo AB'),
    'fdb4': Member('HP Inc'),
    'fdb5': Member('ECSG'),
    'fdb6': Member('GWA Hygiene GmbH'),
    'fdb7': Member('LivaNova USA Inc.'),
    'fdb8': Member('LivaNova USA Inc.'),
    'fdb9': Member('Comcast Cable Corporation'),
    'fdba': Member('Comcast Cable Corporation'),
    'fdbb': Member('Profoto'),
    'fdbc': Member('Emerson'),
    'fdbd': Member('Clover Network, Inc.'),
    'fdbe': Member('California Things Inc.'),
    'fdbf': Member('California Things Inc.'),
    'fdc0': Member('Hunter Douglas'),
    'fdc1': Member('Hunter Douglas'),
    'fdc2': Member('Baidu Online Network Technology (Beijing) Co., Ltd'),
    'fdc3': Member('Baidu Online Network Technology (Beijing) Co., Ltd'),
    'fdc4': Member('Simavita (Aust) Pty Ltd'),
    'fdc5': Member('Automatic Labs'),
    'fdc6': Member('Eli Lilly and Company'),
    'fdc7': Member('Eli Lilly and Company'),
    'fdc8': Member('Hach Danaher'),
    'fdc9': Member('Busch-Jaeger Elektro GmbH'),
    'fdca': Member('Fortin Electronic Systems'),
    'fdcb': Member('Meggitt SA'),
    'fdcc': Member('Shoof Technologies'),
    'fdcd': Member('Qingping Technology (Beijing) Co., Ltd.'),
    'fdce': Member('SENNHEISER electronic GmbH & Co. KG'),
    'fdcf': Member('Nalu Medical, Inc'),
    'fdd0': Member('Huawei Technologies Co., Ltd'),
    'fdd1': Member('Huawei Technologies Co., Ltd'),
    'fdd2': Member('Bose Corporation'),
    'fdd3': Member('FUBA Automotive Electronics GmbH'),
    'fdd4': Member('LX Solutions Pty Limited'),
    'fdd5': Member('Brompton Bicycle Ltd'),
    'fdd6': Member('Ministry of Supply'),
    'fdd7': Member('Emerson'),
    'fdd8': Member('Jiangsu Teranovo Tech Co., Ltd.'),
    'fdd9': Member('Jiangsu Teranovo Tech Co., Ltd.'),
    'fdda': Member('MHCS'),
    'fddb': Member('Samsung Electronics Co., Ltd.'),
    'fddc': Member('4iiii Innovations Inc.'),
    'fddd': Member('Arch Systems Inc'),
    'fdde': Member('Noodle Technology Inc.'),
    'fddf': Member('Harman International'),
    'fde0': Member('John Deere'),
    'fde1': Member('Fortin Electronic Systems'),
    'fde2': Member('Google Inc.'),
    'fde3': Member('Abbott Diabetes Care'),
    'fde4': Member('JUUL Labs, Inc.'),
    'fde5': Member('SMK Corporation'),
    'fde6': Member('Intelletto Technologies Inc'),
    'fde7': Member('SECOM Co., LTD'),
    'fde8': Member('Robert Bosch GmbH'),
    'fde9': Member('Spacesaver Corporation'),
    'fdea': Member('SeeScan, Inc'),
    'fdeb': Member('Syntronix Corporation'),
    'fdec': Member('Mannkind Corporation'),
    'fded': Member('Pole Star'),
    'fdee': Member('Huawei Technologies Co., Ltd.'),
    'fdef': Member('ART AND PROGRAM, INC.'),
    'fdf0': Member('Google Inc.'),
    'fdf1': Member('LAMPLIGHT Co.,Ltd'),
    'fdf2': Member('AMICCOM Electronics Corporation'),
    'fdf3': Member('Amersports'),
    'fdf4': Member('O. E. M. Controls, Inc.'),
    'fdf5': Member('Milwaukee Electric Tools'),
    'fdf6': Member('AIAIAI ApS'),
    'fdf7': Member('HP Inc.'),
    'fdf8': Member('Onvocal'),
    'fdf9': Member('INIA'),
    'fdfa': Member('Tandem Diabetes Care'),
    'fdfb': Member('Tandem Diabetes Care'),
    'fdfc': Member('Optrel AG'),
    'fdfd': Member('RecursiveSoft Inc.'),
    'fdfe': Member('ADHERIUM(NZ) LIMITED'),
    'fdff': Member('OSRAM GmbH'),
    'fe00': Member('Amazon.com Services, Inc.'),
    'fe01': Member('Duracell U.S. Operations Inc.'),
    'fe02': Member('Robert Bosch GmbH'),
    'fe03': Member('Amazon.com Services, Inc.'),
    'fe04': Member('OpenPath Security Inc'),
    'fe05': Member('CORE Transport Technologies NZ Limited'),
    'fe06': Member('Qualcomm Technologies, Inc.'),
    'fe07': Member('Sonos, Inc.'),
    'fe08': Member('Microsoft'),
    'fe09': Member('Pillsy, Inc.'),
    'fe0a': Member('ruwido austria gmbh'),
    'fe0b': Member('ruwido austria gmbh'),
    'fe0c': Member('Procter & Gamble'),
    'fe0d': Member('Procter & Gamble'),
    'fe0e': Member('Setec Pty Ltd'),
    'fe0f': Member('Philips Lighting B.V.'),
    'fe10': Member('Lapis Semiconductor Co., Ltd.'),
    'fe11': Member('GMC-I Messtechnik GmbH'),
    'fe12': Member('M-Way Solutions GmbH'),
    'fe13': Member('Apple Inc.'),
    'fe14': Member('Flextronics International USA Inc.'),
    'fe15': Member('Amazon.com Services, Inc..'),
    'fe16': Member('Footmarks, Inc.'),
    'fe17': Member('Telit Wireless Solutions GmbH'),
    'fe18': Member('Runtime, Inc.'),
    'fe19': Member('Google, Inc'),
    'fe1a': Member('Tyto Life LLC'),
    'fe1b': Member('Tyto Life LLC'),
    'fe1c': Member('NetMedia, Inc.'),
    'fe1d': Member('Illuminati Instrument Corporation'),
    'fe1e': Member('Smart Innovations Co., Ltd'),
    'fe1f': Member('Garmin International, Inc.'),
    'fe20': Member('Emerson'),
    'fe21': Member('Bose Corporation'),
    'fe22': Member('Zoll Medical Corporation'),
    'fe23': Member('Zoll Medical Corporation'),
    'fe24': Member('August Home Inc'),
    'fe25': Member('Apple, Inc.'),
    'fe26': Member('Google'),
    'fe27': Member('Google'),
    'fe28': Member('Ayla Networks'),
    'fe29': Member('Gibson Innovations'),
    'fe2a': Member('DaisyWorks, Inc.'),
    'fe2b': Member('ITT Industries'),
    'fe2c': Member('Google'),
    'fe2d': Member('SMART INNOVATION Co.,Ltd'),
    'fe2e': Member('ERi,Inc.'),
    'fe2f': Member('CRESCO Wireless, Inc'),
    'fe30': Member('Volkswagen AG'),
    'fe31': Member('Volkswagen AG'),
    'fe32': Member('Pro-Mark, Inc.'),
    'fe33': Member('CHIPOLO d.o.o.'),
    'fe34': Member('SmallLoop LLC'),
    'fe35': Member('HUAWEI Technologies Co., Ltd'),
    'fe36': Member('HUAWEI Technologies Co., Ltd'),
    'fe37': Member('Spaceek LTD'),
    'fe38': Member('Spaceek LTD'),
    'fe39': Member('TTS Tooltechnic Systems AG & Co. KG'),
    'fe3a': Member('TTS Tooltechnic Systems AG & Co. KG'),
    'fe3b': Member('Dobly Laboratories'),
    'fe3c': Member('alibaba'),
    'fe3d': Member('BD Medical'),
    'fe3e': Member('BD Medical'),
    'fe3f': Member('Friday Labs Limited'),
    'fe40': Member('Inugo Systems Limited'),
    'fe41': Member('Inugo Systems Limited'),
    'fe42': Member('Nets A/S'),
    'fe43': Member('Andreas Stihl AG & Co. KG'),
    'fe44': Member('SK Telecom'),
    'fe45': Member('Snapchat Inc'),
    'fe46': Member('B&O Play A/S'),
    'fe47': Member('General Motors'),
    'fe48': Member('General Motors'),
    'fe49': Member('SenionLab AB'),
    'fe4a': Member('OMRON HEALTHCARE Co., Ltd.'),
    'fe4b': Member('Philips Lighting B.V.'),
    'fe4c': Member('Volkswagen AG'),
    'fe4d': Member('Casambi Technologies Oy'),
    'fe4e': Member('NTT docomo'),
    'fe4f': Member('Molekule, Inc.'),
    'fe50': Member('Google Inc.'),
    'fe51': Member('SRAM'),
    'fe52': Member('SetPoint Medical'),
    'fe53': Member('3M'),
    'fe54': Member('Motiv, Inc.'),
    'fe55': Member('Google Inc.'),
    'fe56': Member('Google Inc.'),
    'fe57': Member('Dotted Labs'),
    'fe58': Member('Nordic Semiconductor ASA'),
    'fe59': Member('Nordic Semiconductor ASA'),
    'fe5a': Member('Cronologics Corporation'),
    'fe5b': Member('GT-tronics HK Ltd'),
    'fe5c': Member('million hunters GmbH'),
    'fe5d': Member('Grundfos A/S'),
    'fe5e': Member('Plastc Corporation'),
    'fe5f': Member('Eyefi, Inc.'),
    'fe60': Member('Lierda Science & Technology Group Co., Ltd.'),
    'fe61': Member('Logitech International SA'),
    'fe62': Member('Indagem Tech LLC'),
    'fe63': Member('Connected Yard, Inc.'),
    'fe64': Member('Siemens AG'),
    'fe65': Member('CHIPOLO d.o.o.'),
    'fe66': Member('Intel Corporation'),
    'fe67': Member('Lab Sensor Solutions'),
    'fe68': Member('Capsule Technologies Inc.'),
    'fe69': Member('Capsule Technologies Inc.'),
    'fe6a': Member('Kontakt Micro-Location Sp. z o.o.'),
    'fe6b': Member('TASER International, Inc.'),
    'fe6c': Member('TASER International, Inc.'),
    'fe6d': Member('The University of Tokyo'),
    'fe6e': Member('The University of Tokyo'),
    'fe6f': Member('LINE Corporation'),
    'fe70': Member('Beijing Jingdong Century Trading Co., Ltd.'),
    'fe71': Member('Plume Design Inc'),
    'fe72': Member('St. Jude Medical, Inc.'),
    'fe73': Member('St. Jude Medical, Inc.'),
    'fe74': Member('unwire'),
    'fe75': Member('TangoMe'),
    'fe76': Member('TangoMe'),
    'fe77': Member('Hewlett-Packard Company'),
    'fe78': Member('Hewlett-Packard Company'),
    'fe79': Member('Zebra Technologies'),
    'fe7a': Member('Bragi GmbH'),
    'fe7b': Member('Orion Labs, Inc.'),
    'fe7c': Member('Telit Wireless Solutions (Formerly Stollmann E+V GmbH)'),
    'fe7d': Member('Aterica Health Inc.'),
    'fe7e': Member('Awear Solutions Ltd'),
    'fe7f': Member('Doppler Lab'),
    'fe80': Member('Doppler Lab'),
    'fe81': Member('Medtronic Inc.'),
    'fe82': Member('Medtronic Inc.'),
    'fe83': Member('Blue Bite'),
    'fe84': Member('RF Digital Corp'),
    'fe85': Member('RF Digital Corp'),
    'fe86': Member('HUAWEI Technologies Co., Ltd. ( )'),
    'fe87': Member('Qingdao Yeelink Information Technology Co., Ltd. ( )'),
    'fe88': Member('SALTO SYSTEMS S.L.'),
    'fe89': Member('B&O Play A/S'),
    'fe8a': Member('Apple, Inc.'),
    'fe8b': Member('Apple, Inc.'),
    'fe8c': Member('TRON Forum'),
    'fe8d': Member('Interaxon Inc.'),
    'fe8e': Member('ARM Ltd'),
    'fe8f': Member('CSR'),
    'fe90': Member('JUMA'),
    'fe91': Member('Shanghai Imilab Technology Co.,Ltd'),
    'fe92': Member('Jarden Safety & Security'),
    'fe93': Member('OttoQ In'),
    'fe94': Member('OttoQ In'),
    'fe95': Member('Xiaomi Inc.'),
    'fe96': Member('Tesla Motors Inc.'),
    'fe97': Member('Tesla Motors Inc.'),
    'fe98': Member('Currant Inc'),
    'fe99': Member('Currant Inc'),
    'fe9a': Member('Estimote'),
    'fe9b': Member('Samsara Networks, Inc'),
    'fe9c': Member('GSI Laboratories, Inc.'),
    'fe9d': Member('Mobiquity Networks Inc'),
    'fe9e': Member('Dialog Semiconductor B.V.'),
    'fe9f': Member('Google'),
    'fea0': Member('Google'),
    'fea1': Member('Intrepid Control Systems, Inc.'),
    'fea2': Member('Intrepid Control Systems, Inc.'),
    'fea3': Member('ITT Industries'),
    'fea4': Member('Paxton Access Ltd'),
    'fea5': Member('GoPro, Inc.'),
    'fea6': Member('GoPro, Inc.'),
    'fea7': Member('UTC Fire and Security'),
    'fea8': Member('Savant Systems LLC'),
    'fea9': Member('Savant Systems LLC'),
    'feaa': Member('Google'),
    'feab': Member('Nokia'),
    'feac': Member('Nokia'),
    'fead': Member('Nokia'),
    'feae': Member('Nokia'),
    'feaf': Member('Nest Labs Inc'),
    'feb0': Member('Nest Labs Inc'),
    'feb1': Member('Electronics Tomorrow Limited'),
    'feb2': Member('Microsoft Corporation'),
    'feb3': Member('Taobao'),
    'feb4': Member('WiSilica Inc.'),
    'feb5': Member('WiSilica Inc.'),
    'feb6': Member('Vencer Co., Ltd'),
    'feb7': Member('Facebook, Inc.'),
    'feb8': Member('Facebook, Inc.'),
    'feb9': Member('LG Electronics'),
    'feba': Member('Tencent Holdings Limited'),
    'febb': Member('adafruit industries'),
    'febc': Member('Dexcom Inc'),
    'febd': Member('Clover Network, Inc'),
    'febe': Member('Bose Corporation'),
    'febf': Member('Nod, Inc.'),
    'fec0': Member('KDDI Corporation'),
    'fec1': Member('KDDI Corporation'),
    'fec2': Member('Blue Spark Technologies, Inc.'),
    'fec3': Member('360fly, Inc.'),
    'fec4': Member('PLUS Location Systems'),
    'fec5': Member('Realtek Semiconductor Corp.'),
    'fec6': Member('Kocomojo, LLC'),
    'fec7': Member('Apple, Inc.'),
    'fec8': Member('Apple, Inc.'),
    'fec9': Member('Apple, Inc.'),
    'feca': Member('Apple, Inc.'),
    'fecb': Member('Apple, Inc.'),
    'fecc': Member('Apple, Inc.'),
    'fecd': Member('Apple, Inc.'),
    'fece': Member('Apple, Inc.'),
    'fecf': Member('Apple, Inc.'),
    'fed0': Member('Apple, Inc.'),
    'fed1': Member('Apple, Inc.'),
    'fed2': Member('Apple, Inc.'),
    'fed3': Member('Apple, Inc.'),
    'fed4': Member('Apple, Inc.'),
    'fed5': Member('Plantronics Inc.'),
    'fed6': Member('Broadcom'),
    'fed7': Member('Broadcom'),
    'fed8': Member('Google'),
    'fed9': Member('Pebble Technology Corporation'),
    'feda': Member('ISSC Technologies Corp.'),
    'fedb': Member('Perka, Inc.'),
    'fedc': Member('Jawbone'),
    'fedd': Member('Jawbone'),
    'fede': Member('Coin, Inc.'),
    'fedf': Member('Design SHIFT'),
    'fee0': Member('Anhui Huami Information Technology Co., Ltd.'),
    'fee1': Member('Anhui Huami Information Technology Co., Ltd.'),
    'fee2': Member('Anki, Inc.'),
    'fee3': Member('Anki, Inc.'),
    'fee4': Member('Nordic Semiconductor ASA'),
    'fee5': Member('Nordic Semiconductor ASA'),
    'fee6': Member('Silvair, Inc.'),
    'fee7': Member('Tencent Holdings Limited.'),
    'fee8': Member('Quintic Corp.'),
    'fee9': Member('Quintic Corp.'),
    'feea': Member('Swirl Networks, Inc.'),
    'feeb': Member('Swirl Networks, Inc.'),
    'feec': Member('Tile, Inc.'),
    'feed': Member('Tile, Inc.'),
    'feee': Member('Polar Electro Oy'),
    'feef': Member('Polar Electro Oy'),
    'fef0': Member('Intel'),
    'fef1': Member('CSR'),
    'fef2': Member('CSR'),
    'fef3': Member('Google'),
    'fef4': Member('Google'),
    'fef5': Member('Dialog Semiconductor GmbH'),
    'fef6': Member('Wicentric, Inc.'),
    'fef7': Member('Aplix Corporation'),
    'fef8': Member('Aplix Corporation'),
    'fef9': Member('PayPal, Inc.'),
    'fefa': Member('PayPal, Inc.'),
    'fefb': Member('Telit Wireless Solutions (Formerly Stollmann E+V GmbH)'),
    'fefc': Member('Gimbal, Inc.'),
    'fefd': Member('Gimbal, Inc.'),
    'fefe': Member('GN ReSound A/S'),
    'feff': Member('GN Netcom'),
}

descriptors = {
    '2905': Descriptor('Characteristic Aggregate Format',
                       'org.bluetooth.descriptor.gatt.characteristic_aggregate_format'),
    '2900': Descriptor('Characteristic Extended Properties',
                       'org.bluetooth.descriptor.gatt.characteristic_extended_properties'),
    '2904': Descriptor('Characteristic Presentation Format',
                       'org.bluetooth.descriptor.gatt.characteristic_presentation_format'),
    '2901': Descriptor('Characteristic User Description',
                       'org.bluetooth.descriptor.gatt.characteristic_user_description'),
    '2902': Descriptor('Client Characteristic Configuration',
                       'org.bluetooth.descriptor.gatt.client_characteristic_configuration'),
    '290b': Descriptor('Environmental Sensing Configuration',
                       'org.bluetooth.descriptor.es_configuration'),
    '290c': Descriptor('Environmental Sensing Measurement',
                       'org.bluetooth.descriptor.es_measurement'),
    '290d': Descriptor('Environmental Sensing Trigger Setting',
                       'org.bluetooth.descriptor.es_trigger_setting'),
    '2907': Descriptor('External Report Reference',
                       'org.bluetooth.descriptor.external_report_reference'),
    '2909': Descriptor('Number of Digitals',
                       'org.bluetooth.descriptor.number_of_digitals'),
    '2908': Descriptor('Report Reference',
                       'org.bluetooth.descriptor.report_reference'),
    '2903': Descriptor('Server Characteristic Configuration',
                       'org.bluetooth.descriptor.gatt.server_characteristic_configuration'),
    '290e': Descriptor('Time Trigger Setting',
                       'org.bluetooth.descriptor.time_trigger_setting'),
    '2906': Descriptor('Valid Range', 'org.bluetooth.descriptor.valid_range'),
    '290a': Descriptor('Value Trigger Setting',
                       'org.bluetooth.descriptor.value_trigger_setting'),
}

services = {
    '1800': Service('Generic Access', 'org.bluetooth.service.generic_access'),
    '1811': Service('Alert Notification Service',
                    'org.bluetooth.service.alert_notification'),
    '1815': Service('Automation IO', 'org.bluetooth.service.automation_io'),
    '180f': Service('Battery Service',
                    'org.bluetooth.service.battery_service'),
    '1810': Service('Blood Pressure', 'org.bluetooth.service.blood_pressure'),
    '181b': Service('Body Composition',
                    'org.bluetooth.service.body_composition'),
    '181e': Service('Bond Management Service',
                    'org.bluetooth.service.bond_management'),
    '181f': Service('Continuous Glucose Monitoring',
                    'org.bluetooth.service.continuous_glucose_monitoring'),
    '1805': Service('Current Time Service',
                    'org.bluetooth.service.current_time'),
    '1818': Service('Cycling Power', 'org.bluetooth.service.cycling_power'),
    '1816': Service('Cycling Speed and Cadence',
                    'org.bluetooth.service.cycling_speed_and_cadence'),
    '180a': Service('Device Information',
                    'org.bluetooth.service.device_information'),
    '181a': Service('Environmental Sensing',
                    'org.bluetooth.service.environmental_sensing'),
    '1826': Service('Fitness Machine',
                    'org.bluetooth.service.fitness_machine'),
    '1801': Service('Generic Attribute',
                    'org.bluetooth.service.generic_attribute'),
    '1808': Service('Glucose', 'org.bluetooth.service.glucose'),
    '1809': Service('Health Thermometer',
                    'org.bluetooth.service.health_thermometer'),
    '180d': Service('Heart Rate', 'org.bluetooth.service.heart_rate'),
    '1823': Service('HTTP Proxy', 'org.bluetooth.service.http_proxy'),
    '1812': Service('Human Interface Device',
                    'org.bluetooth.service.human_interface_device'),
    '1802': Service('Immediate Alert',
                    'org.bluetooth.service.immediate_alert'),
    '1821': Service('Indoor Positioning',
                    'org.bluetooth.service.indoor_positioning'),
    '183a': Service('Insulin Delivery',
                    'org.bluetooth.service.insulin_delivery'),
    '1820': Service('Internet Protocol Support Service',
                    'org.bluetooth.service.internet_protocol_support'),
    '1803': Service('Link Loss', 'org.bluetooth.service.link_loss'),
    '1819': Service('Location and Navigation',
                    'org.bluetooth.service.location_and_navigation'),
    '1827': Service('Mesh Provisioning Service',
                    'org.bluetooth.service.mesh_provisioning'),
    '1828': Service('Mesh Proxy Service', 'org.bluetooth.service.mesh_proxy'),
    '1807': Service('Next DST Change Service',
                    'org.bluetooth.service.next_dst_change'),
    '1825': Service('Object Transfer Service',
                    'org.bluetooth.service.object_transfer'),
    '180e': Service('Phone Alert Status Service',
                    'org.bluetooth.service.phone_alert_status'),
    '1822': Service('Pulse Oximeter Service',
                    'org.bluetooth.service.pulse_oximeter'),
    '1829': Service('Reconnection Configuration',
                    'org.bluetooth.service.reconnection_configuration'),
    '1806': Service('Reference Time Update Service',
                    'org.bluetooth.service.reference_time_update'),
    '1814': Service('Running Speed and Cadence',
                    'org.bluetooth.service.running_speed_and_cadence'),
    '1813': Service('Scan Parameters',
                    'org.bluetooth.service.scan_parameters'),
    '1824': Service('Transport Discovery',
                    'org.bluetooth.service.transport_discovery'),
    '1804': Service('Tx Power', 'org.bluetooth.service.tx_power'),
    '181c': Service('User Data', 'org.bluetooth.service.user_data'),
    '181d': Service('Weight Scale', 'org.bluetooth.service.weight_scale'),
}

service_classes = {
    '1000': ServiceClass('ServiceDiscoveryServerServiceClassID', 'Bluetooth Core Specification'),
    '1001': ServiceClass('BrowseGroupDescriptorServiceClassID', 'Bluetooth Core Specification'),
    '1101': ServiceClass('SerialPort', 'Serial Port Profile (SPP)'),
    '1102': ServiceClass('LANAccessUsingPPP', 'LAN Access Profile'),
    '1103': ServiceClass('DialupNetworking', 'Dial-up Networking Profile (DUN)'),
    '1104': ServiceClass('IrMCSync', 'Synchronization Profile (SYNC)'),
    '1105': ServiceClass('OBEXObjectPush', 'Object Push Profile (OPP)'),
    '1106': ServiceClass('OBEXFileTransfer', 'File Transfer Profile (FTP)'),
    '1107': ServiceClass('IrMCSyncCommand', 'Synchronization Profile (SYNC)'),
    '1108': ServiceClass('Headset', 'Headset Profile (HSP)'),
    '1109': ServiceClass('CordlessTelephony', 'Cordless Telephony Profile (CTP)'),
    '110A': ServiceClass('AudioSource', 'Advanced Audio Distribution Profile (A2DP)'),
    '110B': ServiceClass('AudioSink', 'Advanced Audio Distribution Profile (A2DP)'),
    '110C': ServiceClass('A/V_RemoteControlTarget', 'Audio/Video Remote Control Profile (AVRCP)'),
    '110D': ServiceClass('AdvancedAudioDistribution', 'Advanced Audio Distribution Profile (A2DP)'),
    '110E': ServiceClass('A/V_RemoteControl', 'Audio/Video Remote Control Profile (AVRCP)'),
    '110F': ServiceClass('A/V_RemoteControlController', 'Audio/Video Remote Control Profile (AVRCP)'),
    '1110': ServiceClass('Intercom', 'Intercom Profile (ICP)'),
    '1111': ServiceClass('Fax', 'Fax Profile (FAX)'),
    '1112': ServiceClass('Headset - Audio Gateway (AG)', 'Headset Profile (HSP)'),
    '1113': ServiceClass('WAP', 'Interoperability Requirements for Bluetooth technology as a WAP, Bluetooth SIG [DEPRECATED]'),
    '1114': ServiceClass('WAP_CLIENT', 'Interoperability Requirements for Bluetooth technology as a WAP, Bluetooth SIG [DEPRECATED]'),
    '1115': ServiceClass('PANU', 'Personal Area Networking Profile (PAN)'),
    '1116': ServiceClass('NAP', 'Personal Area Networking Profile (PAN)'),
    '1117': ServiceClass('GN', 'Personal Area Networking Profile (PAN)'),
    '1118': ServiceClass('DirectPrinting', 'Basic Printing Profile (BPP)'),
    '1119': ServiceClass('ReferencePrinting', 'See Basic Printing Profile (BPP)'),
    '111A': ServiceClass('Basic Imaging Profile', 'Basic Imaging Profile (BIP)'),
    '111B': ServiceClass('ImagingResponder', 'Basic Imaging Profile (BIP)'),
    '111C': ServiceClass('ImagingAutomaticArchive', 'Basic Imaging Profile (BIP)'),
    '111D': ServiceClass('ImagingReferencedObjects', 'Basic Imaging Profile (BIP)'),
    '111E': ServiceClass('Handsfree', 'Hands-Free Profile (HFP)'),
    '111F': ServiceClass('HandsfreeAudioGateway', 'Hands-free Profile (HFP)'),
    '1120': ServiceClass('DirectPrintingReferenceObjectsService', 'Basic Printing Profile (BPP)'),
    '1121': ServiceClass('ReflectedUI', 'Basic Printing Profile (BPP)'),
    '1122': ServiceClass('BasicPrinting', 'Basic Printing Profile (BPP)'),
    '1123': ServiceClass('PrintingStatus', 'Basic Printing Profile (BPP)'),
    '1124': ServiceClass('HumanInterfaceDeviceService', 'Human Interface Device (HID)'),
    '1125': ServiceClass('HardcopyCableReplacement', 'Hardcopy Cable Replacement Profile (HCRP)'),
    '1126': ServiceClass('HCR_Print', 'Hardcopy Cable Replacement Profile (HCRP)'),
    '1127': ServiceClass('HCR_Scan', 'Hardcopy Cable Replacement Profile (HCRP)'),
    '1128': ServiceClass('Common_ISDN_Access', 'Common ISDN Access Profile (CIP)'),
    '112D': ServiceClass('SIM_Access', 'SIM Access Profile (SAP)'),
    '112E': ServiceClass('Phonebook Access - PCE', 'Phonebook Access Profile (PBAP)'),
    '112F': ServiceClass('Phonebook Access - PSE', 'Phonebook Access Profile (PBAP)'),
    '1130': ServiceClass('Phonebook Access', 'Phonebook Access Profile (PBAP)'),
    '1131': ServiceClass('Headset - HS', 'Headset Profile (HSP)'),
    '1132': ServiceClass('Message Access Server', 'Message Access Profile (MAP)'),
    '1133': ServiceClass('Message Notification Server', 'Message Access Profile (MAP)'),
    '1134': ServiceClass('Message Access Profile', 'Message Access Profile (MAP)'),
    '1135': ServiceClass('GNSS', 'Global Navigation Satellite System Profile (GNSS)'),
    '1136': ServiceClass('GNSS_Server', 'Global Navigation Satellite System Profile (GNSS)'),
    '1137': ServiceClass('​3D Display', '​3D Synchronization Profile (3DSP)'),
    '1138': ServiceClass('3D Glasses', '3D Synchronization Profile (3DSP)'),
    '1139': ServiceClass('3D Synchronization', '3D Synchronization Profile (3DSP)'),
    '113A': ServiceClass('MPS Profile UUID', 'Multi-Profile Specification (MPS)'),
    '113B': ServiceClass('MPS SC UUID', 'Multi-Profile Specification (MPS)'),
    '113C': ServiceClass('CTN Access Service', 'Calendar, Task, and Notes (CTN) Profile'),
    '113D': ServiceClass('CTN Notification Service', 'Calendar Tasks and Notes (CTN) Profile'),
    '113E': ServiceClass('CTN Profile', 'Calendar Tasks and Notes (CTN) Profile'),
    '1200': ServiceClass('PnPInformation', 'Device Identification (DID)'),
    '1201': ServiceClass('GenericNetworking', 'N/A'),
    '1202': ServiceClass('GenericFileTransfer', 'N/A'),
    '1203': ServiceClass('GenericAudio', 'N/A'),
    '1204': ServiceClass('GenericTelephony', 'N/A'),
    '1205': ServiceClass('UPNP_Service', 'Enhanced Service Discovery Profile (ESDP) [DEPRECATED]'),
    '1206': ServiceClass('UPNP_IP_Service', 'Enhanced Service Discovery Profile (ESDP) [DEPRECATED]'),
    '1300': ServiceClass('ESDP_UPNP_IP_PAN', 'Enhanced Service Discovery Profile (ESDP) [DEPRECATED]'),
    '1301': ServiceClass('ESDP_UPNP_IP_LAP', 'Enhanced Service Discovery Profile (ESDP)[DEPRECATED]'),
    '1302': ServiceClass('ESDP_UPNP_L2CAP', 'Enhanced Service Discovery Profile (ESDP)[DEPRECATED]'),
    '1303': ServiceClass('VideoSource', 'Video Distribution Profile (VDP)'),
    '1304': ServiceClass('VideoSink', 'Video Distribution Profile (VDP)'),
    '1305': ServiceClass('VideoDistribution', 'Video Distribution Profile (VDP)'),
    '1400': ServiceClass('HDP', 'Health Device Profile'),
    '1401': ServiceClass('HDP Source', 'Health Device Profile (HDP)'),
    '1402': ServiceClass('HDP Sink', 'Health Device Profile (HDP)')
}

service_protocols = {
    '0000': ServiceProtocol('BASE_UUID', 'Bluetooth Core Specification'),
    '0001': ServiceProtocol('SDP', 'Bluetooth Core Specification'),
    '0002': ServiceProtocol('UDP', '[NO USE BY PROFILES]'),
    '0003': ServiceProtocol('RFCOMM', 'RFCOMM with TS 07.10'),
    '0004': ServiceProtocol('TCP', '[NO USE BY PROFILES]'),
    '0005': ServiceProtocol('TCS-BIN', 'Telephony Control Specification / TCS Binary [DEPRECATED]'),
    '0006': ServiceProtocol('TCS-AT', '[NO USE BY PROFILES]'),
    '0007': ServiceProtocol('ATT', 'Attribute Protocol'),
    '0008': ServiceProtocol('OBEX', 'IrDA Interoperability'),
    '0009': ServiceProtocol('IP', '[NO USE BY PROFILES]'),
    '000a': ServiceProtocol('FTP', '[NO USE BY PROFILES]'),
    '000c': ServiceProtocol('HTTP', '[NO USE BY PROFILES]'),
    '000e': ServiceProtocol('WSP', '[NO USE BY PROFILES]'),
    '000f': ServiceProtocol('BNEP', 'Bluetooth Network Encapsulation Protocol (BNEP)'),
    '0010': ServiceProtocol('UPNP', 'Extended Service Discovery Profile (ESDP) [DEPRECATED]'),
    '0011': ServiceProtocol('HIDP', 'Human Interface Device Profile (HID)'),
    '0012': ServiceProtocol('HardcopyControlChannel', 'Hardcopy Cable Replacement Profile (HCRP)'),
    '0014': ServiceProtocol('HardcopyDataChannel', 'See Hardcopy Cable Replacement Profile (HCRP)'),
    '0016': ServiceProtocol('HardcopyNotification', 'Hardcopy Cable Replacement Profile (HCRP)'),
    '0017': ServiceProtocol('AVCTP', 'Audio/Video Control Transport Protocol (AVCTP)'),
    '0019': ServiceProtocol('AVDTP', 'Audio/Video Distribution Transport Protocol (AVDTP)'),
    '001b': ServiceProtocol('CMTP', 'Common ISDN Access Profile (CIP) [DEPRECATED]'),
    '001e': ServiceProtocol('MCAPControlChannel', 'Multi-Channel Adaptation Protocol (MCAP)'),
    '001f': ServiceProtocol('MCAPDataChannel', 'Multi-Channel Adaptation Protocol (MCAP)'),
    '0100': ServiceProtocol('L2CAP', 'Bluetooth Core Specification'),
}

custom_services = {
    '7905f431-b5ce-4e99-a40f-4b1e122d00d0':
        Service('Apple Notification Center Service', ''),
    'adabfb00-6e7d-4601-bda2-bffaa68956ba':
        Service('Fitbit Control Service', ''),
    '558dfa00-4fa8-4105-9f02-4eaa93e62980':
        Service('Fitbit Data Service', ''),
    '16bcfd00-253f-c348-e831-0db3e334d580':
        Service('Fitbit Service', ''),
    '381c08ec-57ee-0611-0601-02362e315055':
        Service('Mio fuse DFU', ''),
    '381c08ec-57ee-0611-0601-02312e315055':
        Service('Mio link DFU', ''),
    '381c08ec-57ee-0611-0601-02332e315055':
        Service('Mio velo DFU', ''),
    '6c721550-5bf1-4f64-9170-381c08ec57ee':
        Service('Alpha2 DFU', ''),
    '6c721530-5bf1-4f64-9170-381c08ec57ee':
        Service('DFU', ''),
    '6c721838-5bf1-4f64-9170-381c08ec57ee':
        Service('Mio sports', '')
}

custom_characteristics = {
    '9fbf120d-6301-42d9-8c58-25e699a21dbd':
        Characteristic('Notification Source (Apple Notification Center Service)', ''),
    '69d1d8f3-45e1-49a8-9821-9bbdfdaad9d':
        Characteristic('Control Point (Apple Notification Center Service)', ''),
    '22eac6e9-24d6-4bb5-be44-b36ace7c7bfb':
        Characteristic('Data Source (Apple Notification Center Service)', ''),
    'adabfb01-6e7d-4601-bda2-bffaa68956ba':
        Characteristic('Fitbit Control read characteristic', ''),
    'adabfb02-6e7d-4601-bda2-bffaa68956ba':
        Characteristic('Fitbit Control wrtie characteristic', ''),
    'adabfb04-6e7d-4601-bda2-bffaa68956ba':
        Characteristic('Fitbit Control characteristic', ''),
    '558dfa01-4fa8-4105-9f02-4eaa93e62980':
        Characteristic('Fitbit Data characteristic', ''),
    '16bcfd01-253f-c348-e831-0db3e334d580':
        Characteristic('Fitbit characteristic', ''),
    '16bcfd02-253f-c348-e831-0db3e334d580':
        Characteristic('Fitbit characteristic', ''),
    '16bcfd03-253f-c348-e831-0db3e334d580':
        Characteristic('Fitbit characteristic', ''),
    '16bcfd04-253f-c348-e831-0db3e334d580':
        Characteristic('Fitbit characteristic', ''),
    '6c721531-5bf1-4f64-9170-381c08ec57ee':
        Characteristic('DFU controlpoint', ''),
    '6c721532-5bf1-4f64-9170-381c08ec57ee':
        Characteristic('DFU packet', ''),
    '00001533-1212-efde-1523-785feabcd123':
        Characteristic('DFU status report', ''),
    '6c722a84-5bf1-4f64-9170-381c08ec57ee':
        Characteristic('Mio record', ''),
    '6c722a83-5bf1-4f64-9170-381c08ec57ee':
        Characteristic('Mio senser', ''),
    '6c722a80-5bf1-4f64-9170-381c08ec57ee':
        Characteristic('Mio sport msg', ''),
    '6c722a82-5bf1-4f64-9170-381c08ec57ee':
        Characteristic('Mio sport msg resp', ''),
    '6c721551-5bf1-4f64-9170-381c08ec57ee':
        Characteristic('Alpha2 DFU controlpoint', ''),
    '6c721553-5bf1-4f64-9170-381c08ec57ee':
        Characteristic('Alpha2 DFU packet', ''),
    '6c721552-5bf1-4f64-9170-381c08ec57ee':
        Characteristic('Alpha2 DFU sendpacket', '')
}

sig_items = [
    members,
    services,
    characteristics,
    descriptors,
    service_classes,
    service_protocols
]

custom_items = [
    custom_services,
    custom_characteristics
]
